// 1. Captura una excepción utilizando try-catch
// 2. Captura una excepción utilizando try-catch y finally
// 3. Lanza una excepción genérica
let person 

try {
    console.log(person.alias);
} catch (error) {
    console.log("Se ha producido un error", error.message);
}finally{
    console.log("Este se ejecuta siempre");
    
}


// 4. Crea una excepción personalizada
// 5. Lanza una excepción personalizada




// 6. Lanza varias excepciones según una lógica definida

// 7. Captura varias excepciones en un mismo try-catch

// 8. Crea un bucle que intente transformar a float cada valor y capture y muestre los errores

// 9. Crea una función que verifique si un objeto tiene una propiedad específica y lance una excepción personalizada

// 10. Crea una función que realice reintentos en caso de error hasta un máximo de 10